import { writeFile, mkdir } from "node:fs/promises";
import { resolve, basename } from "node:path";

export async function generateNodeTests(repoRoot: string, sourceFiles: string[], outDir = ".mdt/out/tests"): Promise<{ files: string[] }> {
	await mkdir(resolve(repoRoot, outDir), { recursive: true });
	const files: string[] = [];
	for (const src of sourceFiles) {
		const name = basename(src).replace(/[.](ts|js|tsx|jsx)$/i, "");
		const file = resolve(repoRoot, outDir, `${name}.mdt.test.js`);
		const content = `// GENERATED BY MDT — REVIEW\nimport test from 'node:test';\nimport assert from 'node:assert/strict';\n\ntest('${name} — smoke', () => {\n  assert.ok(true);\n});\n`;
		await writeFile(file, content, "utf8");
		files.push(file);
	}
	return { files };
}